import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Admin",
      email: "asqarrsl@gmail.com",
      mobile: "+94772099072",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Puma",
        logo: "/images/logo1.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "User",
      email: "ashiquearrasool@mail.com",
      mobile: "+94772099078",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Straight long coat",
      category: "Womens",
      image: "/images/5xN6v24411.jpg",
      price: 120,
      countInStock: 10,
      brand: "Brand",
      rating: 4.5,
      numReviews: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s",
    },
    {
      name: "Strip Knitwear for women",
      category: "Womens",
      image: "/images/9j0ay19709.jpg",
      price: 100,
      countInStock: 20,
      brand: "Brand",
      rating: 4.0,
      numReviews: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s",
    },
    {
      name: "Printed Rose Petal Shirt",
      category: "Womens",
      image: "/images/heO2f18806.jpg",
      price: 100,
      countInStock: 20,
      brand: "Brand",
      rating: 4.0,
      numReviews: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s",
    },
    {
      name: "Women Magnet Buckle Quartz Watch",
      category: "Watches",
      image: "/images/2Ggn319911.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Alloy Military Quartz watch man",
      category: "Watches",
      image: "/images/1sjR619111.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s,",
    },
    {
      name: "Mesh Breathable Mens Sneakers",
      category: "Shoes",
      image: "/images/2w32T17111.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, ",
    },
    {
      name: "Light Man Lace-up Shoes",
      category: "Shoes",
      image: "/images/7R13s17112.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, ",
    },
    {
      name: "Brock Knitted Mesh Casual Oxford Sneakers",
      category: "Shoes",
      image: "/images/8qhcn17212.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, ",
    },
    {
      name: "Casual Breathable Outdoor Kids Sneakers",
      category: "Shoes",
      image: "/images/9fyvN19411.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, ",
    },
    {
      name: "Casual Tracksuit Children Boy",
      category: "Kids",
      image: "/images/6J2Xd17210.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Fashion Plaid Boy Clothing Set",
      category: "Kids",
      image: "/images/7qQLv17911.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Men Polo Casual Shirt",
      category: "Mens",
      image: "/images/0Ygma19611.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Juventus Henley Neck Tshirt",
      category: "Mens",
      image: "/images/4MSZL17612.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Dotted Casual Shirt for men",
      category: "Mens",
      image: "/images/3P1Yv19211.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Casual Cotton Jeans for Men",
      category: "Mens",
      image: "/images/3MBuE19511.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
